[tool.poetry]
name = "callament"
version = "0.0.1"
description = "Callament helps people contact their representatives."
authors = ["Tim Weber"]
license = "AGPL-3.0"

[tool.poetry.dependencies]
python = "^3.7"
fastapi = "^0.78"

[tool.poetry.dev-dependencies]
uvicorn = {extras = ["standard"], version = "^0.18.2"}
flake8 = "^4.0.1"
flake8-quotes = "^3.3.1"
mypy = "^0.971"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
