# Options ending in `_duration` or `_timeout` (or simply named `duration` or
# `timeout`) should be specified in seconds, unless noted otherwise.

# Options ending in `_limit` (or simply named `limit`) should contain a string
# compatible to the notation used by the `limits` Python library. See
# <https://limits.readthedocs.io/en/latest/quickstart.html#rate-limit-string-notation>.
# If a limit is being documented as applying "per IP address", the exact
# definition may be more complex, especially when it comes to IPv6.


# Campaign metadata.
campaign:

  # The name of the campaign.
  name: Stop Scanning Me!


# User authentication.
authentication:

  # A user's session, usually identified via a one-time code sent via SMS. These
  # are managed via a non-permanent JWT session cookie that will get deleted
  # once the user closes their browser window or logs out manually.
  session:

    # How long until the session times out due to inactivity. Any API request
    # with a valid token will reset this timeout.
    inactivity_timeout: 7200

    # How long until the session times out regardless of any activity. This
    # timeout does not reset. A new verification will need to take place once it
    # has been reached. Its main purpose is to ensure that the user still owns
    # the phone number, even if they artificially kept the session alive for
    # days or even months.
    authentication_timeout: 86400


# Options regarding phone calls and SMS.
telephony:

  # Verifying phone numbers by sending an SMS to that number.
  sms_verification:

    # How long until verification codes sent via SMS expire.
    timeout: 900

    # After this many codes have been sent to a certain number without any of
    # them being converted into a Session Token, add the number to a block list.
    # It cannot be used again before being manually unlocked by an admin. This
    # is to prevent spamming a victim with codes, incurring costs.
    max_unused: 3

    # How many verifications may be requested (possibly for different phone
    # numbers, think call party behind a NAT) per IP address?
    per_ip_limit: 3 per second, 10 per 6 hours

    # How many SMS messages may the system send overall?
    send_limit: 5 per second, 100 per hour


# Localization options.
l10n:
  # The languages your campaign is available in. You have to use a language tag
  # as defined in RFC 5646. (Try not to be over-specific though. `en-UK` is
  # fine, `de-Latn-DE-1996` might be overdoing it and cause issues when auto-
  # detecting a user's language.) The first value in this list will be the
  # default if the user's browser claims they accept `*` (i.e. "any language").
  # You therefore probably want to make sure that the first value here is
  # identical to the `default_language` set below.
  languages: [ en, de-AT ]

  # Which language to fall back to if there is no localized message available
  # for the user's language. Every string defined under `strings` needs to have
  # a value provided for this language. This is also what the language auto-
  # detection falls back to if the user does not specify a supported language
  # in their preferences. This has to be one of the languages defined in the
  # `languages` list above.
  default_language: en

  # Which MMDB geo-IP lookup database to use. Supply the file name relative to
  # the working directory you're invoking the application from, or use an
  # absolute path. If you do not set this value, a bundled version of
  # <https://pypi.org/project/python-geoacumen/> will be used.
  # You may choose any MMDB, as long as the lookup results in a dict with a key
  # `country` that contains either the ISO code as a string, or a sub-dict with
  # a key `iso_code` that then contains the ISO code.
  # geo_mmdb: Geoacumen-Country.mmdb

  # Localized/translated strings.
  # Each of the keys below `strings` defines a translateable string. You may
  # either set the value to a simple string, in which case it will be used
  # regardless of the user's language (good for single-language campaigns), but
  # the recommended way is to provide a mapping of languages to strings.
  # TODO: Explain further.
  # The following placeholders are available in all of the strings:
  #   {campaign}  The configured campaign name.
  strings:

    # Name of the campaign. This will be available in every other l10n string
    # via the {campaign} placeholder.
    campaign_name: Stop Scanning Me

    # Content of SMS sent to users when we need to verify their phone number.
    # {code} will be replaced by a six-digit random number.
    phone_number_verification_sms:
      en: "{code} is your {campaign} verification code. If you think you have received this message in error, simply ignore it."

  frontend_strings:
    title:
      en: Call your MEP! Lorem ipsum dolor sit
    call.start-call-btn.title:
      en: Start Call
    call.start-call-btn.subtitle:
      en: Free of charge
    call.call-now-btn.title:
      en: Call Now
    call.call-now-btn.subtitle:
      en: Free of charge
    call.call-later-btn.title:
      en: Call later
    call.home.title:
      en: Contact your Member of the European Parliament. You can call now or schedule
        calls in the future.
    call.home.descriptions.0.text:
      en: We will call you right away and connect you for free.
    call.home.descriptions.1.text:
      en: Rorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero
        et velit interdum.
    verification.title:
      en: Verify your phone number
    verification.enterNumber.description:
      en: Please enter your own phone number and we will send you a one time password
        to verify your number.
    verification.enterNumber.numberFieldLabel:
      en: Enter your phone number
    verification.enterNumber.policy:
      en: I have read and accept the
    verification.enterNumber.policyLinkText:
      en: Privacy Policy
    verification.enterNumber.sendCode:
      en: Send Code
    verification.enterCode.description:
      en: Please check you phone. We've sent a code to {{ number }}.
    verification.enterCode.notYourNumber:
      en: If this is not your number click
    verification.enterCode.codeFieldLabel:
      en: Enter your Code
    verification.enterCode.verifyCode:
      en: Verify
    verification.success.message:
      en: 'Succesfully verified with the number: {{ number }}'
    callSetup.title:
      en: Your call is being set up
    callSetup.description:
      en: Please have your mobile phone ready. We will call you right away and connect
        you with {{ mep }}.
    feedback.title:
      en: Feedback
    feedback.convincingQuestion:
      en: Were you able to convince the person?
    feedback.convincingQuestionFeedback.yes:
      en: 'Yes'
    feedback.convincingQuestionFeedback.likeleyYes:
      en: likeley yes
    feedback.convincingQuestionFeedback.likeleyNo:
      en: likeley no
    feedback.convincingQuestionFeedback.no:
      en: 'No'
    feedback.technicalProblemsQuestion:
      en: There were technical problems
    feedback.additionalFeedbackQuestion:
      en: Additional feedback
    feedback.additionalFeedbackPlaceholder:
      en: If you have any additional feedback, please type it in here...
    feedback.submit:
      en: Submit
    select-mep.autorenew:
      en: Choose another MEP
    select-mep.country:
      en: Country
    talkingPoints.title:
      en: Talking Points
    talkingPoints.points.0.title:
      en: Argument 1
    talkingPoints.points.0.body:
      en: Norem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero
        et velit interdum, ac aliquet odio mattis.
    talkingPoints.points.1.title:
      en: Argument 2
    talkingPoints.points.1.body:
      en: Norem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero
        et velit interdum, ac aliquet odio mattis.
    talkingPoints.points.2.title:
      en: Argument 3
    talkingPoints.points.2.body:
      en: Norem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero
        et velit interdum, ac aliquet odio mattis.
    talkingPoints.points.3.title:
      en: Argument 4
    talkingPoints.points.3.body:
      en: Norem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero
        et velit interdum, ac aliquet odio mattis.
    languages.available.0.name:
      en: English
    languages.available.1.name:
      en: Français
    footer.contentHtml:
      en: <a href="https://dearmep.eu" target="_blank">DearMEP</a>&nbsp;powered by&nbsp;<a
        href="https://epicenter.works" target="_blank">Epicenter.works</a>
    schedule.title:
      en: Schedule a call
    schedule.description:
      en: 'Plan now to talk to a politican later! Select a day and time:'
    schedule.scheduleAsText:
      en: We will give you a ring every {{ timeSlots }} at your number to connect you
        with a politician from {{ country }}.
    schedule.timeSlot:
      en: "{{ dayOfWeek }} around {{ time }}"
    schedule.and:
      en: and
    schedule.around:
      en: around
    schedule.days.0:
      en: Sunday
    schedule.days.1:
      en: Monday
    schedule.days.2:
      en: Tuesday
    schedule.days.3:
      en: Wednesday
    schedule.days.4:
      en: Thursday
    schedule.days.5:
      en: Friday
    schedule.days.6:
      en: Saturday
    schedule.days-short.0:
      en: Su
    schedule.days-short.1:
      en: Mo
    schedule.days-short.2:
      en: Tu
    schedule.days-short.3:
      en: We
    schedule.days-short.4:
      en: Th
    schedule.days-short.5:
      en: Fr
    schedule.days-short.6:
      en: Sa
    schedule.schedule-btn.title:
      en: Confirm
    schedule.schedule-btn.subtitle:
      en: Free of charge
    schedule.timezone:
      en: 'Time: {{ zone }}'
    util.join.delimiter:
      en: ", "
    util.join.lastDelimiter:
      en: " and "
    countries.BE:
      en: Belgium
    countries.BG:
      en: Bulgaria
    countries.CZ:
      en: Czechia
    countries.DK:
      en: Denmark
    countries.DE:
      en: Germany
    countries.EE:
      en: Estonia
    countries.IE:
      en: Estonia
    countries.GR:
      en: Greece
    countries.ES:
      en: Spain
    countries.FR:
      en: France
    countries.HR:
      en: Croatia
    countries.IT:
      en: Italy
    countries.CY:
      en: Cyprus
    countries.LV:
      en: Latvia
    countries.LT:
      en: Lithuania
    countries.LU:
      en: Luxembourg
    countries.HU:
      en: Hungary
    countries.MT:
      en: Malta
    countries.NL:
      en: Netherlands
    countries.AT:
      en: Austria
    countries.PL:
      en: Poland
    countries.PT:
      en: Portugal
    countries.RO:
      en: Romania
    countries.SI:
      en: Slovenia
    countries.SK:
      en: Slovakia
    countries.FI:
      en: Finland
    countries.SE:
      en: Sweden
